name: Docker Series Builds

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2  
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD https://docker.edwintrakselis.com
    - name: update local repo
      run: | 
        git clone git@github.com:etrakselis/CI_Pipeline_Test.git           
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}     
    - name: docker build mysite-nginx2
      run: |
        docker build -t mysite-nginx2:v${{ steps.buildnumber.outputs.build_number }} .  
    - name: docker tag the image
      run: |
        docker tag mysite-nginx2:v${{ steps.buildnumber.outputs.build_number }} docker.edwintrakselis.com/mysite-nginx2:v${{ steps.buildnumber.outputs.build_number }}
    - name: docker push
      run: |
        docker push docker.edwintrakselis.com/mysite-nginx2:v${{ steps.buildnumber.outputs.build_number }}
    - name: Reset Deployment
      run: |
        sudo kubectl rollout restart deployments mysite-nginx2  
      
